should = require 'should'
global.IO = require '../coffee/IO.coffee'
{Base64IO} = require '../coffee/Troxel.io.coffee'

chr_knight     = 'FBUUAP9AlUAAqKio/5JAAKioqP+SQADc3Nz/kkAA3Nzc//9A/0DSQACoqKj/kkAARERE/5JAAERERP+SQABERET/kkAARERE/5JAANzc3P//QP9AqkAAqKio/6ZAAHR0dP+SQAB0dHT/kkAAqKio/5JAAKioqP+mQADc3Nz//0D/QNJAAERERP+SQABERET//0DuQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAMyYZP+SQABERET/kkAAzJhk//9A/0CWQAD8zJj//0DGQAB0dHT/kkAAiIiI//9A2kAAMJhk/81AggB0dHT/j0AAdHR0/0AAdHR0/0AAdHR0/45AgQB0dHT/QIEAdHR0/45AAHR0dP9AAHR0dP9AAHR0dP+PQIIAdHR0/5FAAHR0dP//QNhAAACYMP8AMMww/wAAmDD/ADDMMP8AAJgw/6NAAPyYAP8A/MyY/5FAAPyYAP8AAJgw/wD8mAD/j0AA/JgA/0CCAPyYAP+OQAD8mAD/APzMMP+BAPyYAP8AiIiI/45AAPyYAP8AzJgw/4IA/JgA/wB0dHT/jEAAqKio/4EA/JgA/wCIiIj/gQD8mAD/AHR0dP+MQACoqKj/APyYAP8AiIiI/wD8mAD/AHR0dP8A/JgA/wB0dHT/jUCEAHR0dP//QLBAAJhkMP+SQACYZDD/kkAA/MyY/5BAgQAwzDD/APyYAP+BADDMMP+PQAAwzDD/AACYMP8AMMww/5BAADDMMP8A/JgA/wAwzDD/j0CEAPyYAP+PQAD8mGT/gwD8mAD/jkAAEBAQ/4IA/JgA/4EAdHR0/41AhAD8mAD/AHR0dP+LQACoqKj/AIiIiP+EAPyYAP8AdHR0/4tAAKioqP+EAPyYAP8AdHR0/41AAIiIiP+CAPyYAP8AdHR0/49AggB0dHT//0DXQIQAAJgw/49AAACYMP8A/JgA/wAAmDD/kEAAAJgw/wD8mAD/AACYMP+QQAAwzAD/gwD8mAD/jkAA/Jhk/4IA/JgA/49AAPzMmP+BAPyYAP8AdHR0/45AhAD8mAD/gQB0dHT/i0AAqKio/4UA/JgA/wB0dHT/i0AAqKio/4QA/JgA/wB0dHT/jUAAiIiI/4IA/JgA/wB0dHT/j0CCAIiIiP//QNdAhAAwzDD/j0AAMMww/wD8mAD/ADDMMP+QQAAwzDD/APyYAP8AMMww/5BAADDMMP+DAPyYAP+OQAD8zJj/ggD8mAD/j0AA/MyY/4EA/JgA/wB0dHT/j0CDAPyYAP+BAHR0dP+LQAC4uLj/AIiIiP+EAPyYAP8AdHR0/4tAALi4uP+EAPyYAP8AdHR0/41AAIiIiP+CAPyYAP8AdHR0/49AggCIiIj//0CdQACYZDD/kkAAmGQw/5JAAPzMmP+QQIEAAJgw/wD8mAD/gQAAmDD/j0AAAJgw/wAwzDD/AACYMP+QQAAwzDD/gQAwmGT/AGSYMP8A/JgA/41AgwD8mAD/APyYMP+PQAD8zJj/gwD8mAD/jkAAEBAQ/4IA/JgA/4EAdHR0/41AhAD8mAD/AHR0dP+LQAC4uLj/AIiIiP+EAPyYAP8AdHR0/4tAALi4uP+EAPyYAP8AdHR0/41AAIiIiP+CAPyYAP8AdHR0/49AggCIiIj//0DXQAAwzDD/AACYMP8AMMww/wAAmDD/ADDMMP+TQAD8mAD/jkAA/JgA/5JAAPyYAP8AAJgw/4IA/JgA/41AAPyYAP9AAPyYMP+BAPyYAP+OQIMA/JgA/wCIiIj/jkAA/JgA/wDMmDD/ggD8mAD/AHR0dP+MQAC4uLj/gQD8mAD/AIiIiP+BAPyYAP8AdHR0/4xAAOzs7P8A/JgA/wCIiIj/APyYAP8AiIiI/wD8mAD/AHR0dP+NQIIAiIiI/4EAdHR0//9A7EAA/MyY/4FAAPyYAP+jQAD8zJj/gUAA/JgA/6RAAPyYAP+QQIIAiIiI/49AAIiIiP9AAIiIiP9AAIiIiP+OQIEAiIiI/0CBAIiIiP+OQACIiIj/QACIiIj/QACIiIj/j0CCAIiIiP+RQACIiIj//0DuQAD8zJj/gUAA/JgA/6VAAPyYAP//QIhAAIiIiP+SQACoqKj//0DJQAD8mAD//0D/QP9AtUAA/JgA/6RAAPyYAP//QP9A/0CPQAD8mAD//0D/QP9A/0D/QP9A/0D/QPtA'
chr_knight_rpx = 'FBQVAP9AqUAAmGQw/7pAAJhkMP/OQACYZDD//0D/QIJAAJhkMP+6QACYZDD/zkAAmGQw//9A/0CCQAD8zJj/ukAA/MyY/85AAJhkMP//QLVAAPyYAP+jQAD8zJj/gUAA/JgA/41AADDMMP8AAJgw/wAwzDD/AACYMP8AMMww/45AgQAAmDD/APyYAP+BAACYMP+OQIQAMMww/45AhAAAmDD/jkCBADDMMP8A/JgA/4EAMMww/45AAACYMP8AMMww/wAAmDD/ADDMMP8AAJgw/6RAAPzMmP+SQACYZDD//0CgQAD8mAD/pEAA/MyY/4FAAPyYAP+mQAD8mAD/jkAAAJgw/wAwzDD/AACYMP+QQAAwzDD/APyYAP8AMMww/5BAAACYMP8A/JgA/wAAmDD/kEAAMMww/wAAmDD/ADDMMP+lQAAwmGT/pkAAmGQw//9Ai0AA/JgA/81AAPzMmP+BQAD8mAD/jkAA/JgA/5JAADDMMP+BADCYZP8AZJgw/wD8mAD/jkAAMMww/wD8mAD/ADDMMP+QQAAAmDD/APyYAP8AAJgw/5BAADDMMP8A/JgA/wAwzDD/kEAA/JgA/wD8zJj/ukAAmGQw/6ZAAKioqP/2QAD8mAD/qEAA/JgA/6NAAPyYAP8AAJgw/4IA/JgA/41AgwD8mAD/APyYMP+PQAAwzDD/gwD8mAD/jkAAMMwA/4MA/JgA/41AhAD8mAD/j0AA/JgA/wAAmDD/APyYAP+5QACYZDD/ukAAqKio//9An0AA/JgA/49AAPyYAP9AAPyYMP+BAPyYAP+PQAD8zJj/gwD8mAD/jkAA/MyY/4IA/JgA/49AAPyYZP+CAPyYAP+PQAD8mGT/gwD8mAD/jUAA/JgA/0CCAPyYAP+4QACYZDD/pkAAdHR0/5JAAERERP+SQACoqKj//0CJQIIAiIiI/49AgwD8mAD/AIiIiP+PQAAQEBD/ggD8mAD/gQB0dHT/jUAA/MyY/4EA/JgA/wB0dHT/j0AA/MyY/4EA/JgA/wB0dHT/j0AAEBAQ/4IA/JgA/4EAdHR0/4xAAPyYAP8A/Mww/4EA/JgA/wCIiIj/j0CCAHR0dP+lQADMmGT/kkAARERE/5JAAHR0dP+SQABERET/kkAAqKio//9AiEAAiIiI/0AAiIiI/0AAiIiI/45AAPyYAP8AzJgw/4IA/JgA/wB0dHT/jkCEAPyYAP8AdHR0/41AgwD8mAD/gQB0dHT/jECEAPyYAP+BAHR0dP+NQIQA/JgA/wB0dHT/jEAA/JgA/wDMmDD/ggD8mAD/AHR0dP+NQAB0dHT/QAB0dHT/QAB0dHT/pEAARERE/5JAAERERP+SQACoqKj/kkAARERE/5JAANzc3P//QIhAgQCIiIj/QIEAiIiI/41AALi4uP+BAPyYAP8AiIiI/4EA/JgA/wB0dHT/jEAAuLi4/wCIiIj/hAD8mAD/AHR0dP+LQAC4uLj/AIiIiP+EAPyYAP8AdHR0/4tAAKioqP+FAPyYAP8AdHR0/4tAAKioqP8AiIiI/4QA/JgA/wB0dHT/i0AAqKio/4EA/JgA/wCIiIj/gQD8mAD/AHR0dP+NQIEAdHR0/0CBAHR0dP+kQADMmGT/pkAAqKio/5JAAERERP+SQADc3Nz//0CIQACIiIj/QACIiIj/QACIiIj/jUAA7Ozs/wD8mAD/AIiIiP8A/JgA/wCIiIj/APyYAP8AdHR0/4xAALi4uP+EAPyYAP8AdHR0/4xAALi4uP+EAPyYAP8AdHR0/4xAAKioqP+EAPyYAP8AdHR0/4xAAKioqP+EAPyYAP8AdHR0/4xAAKioqP8A/JgA/wCIiIj/APyYAP8AdHR0/wD8mAD/AHR0dP+NQAB0dHT/QAB0dHT/QAB0dHT/4EAA3Nzc//9AnUCCAIiIiP+PQIIAiIiI/4EAdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AhAB0dHT/j0CCAHR0dP/NQADc3Nz//0CeQACIiIj/kkAAiIiI/6VAggCIiIj/kECCAIiIiP+QQIIAiIiI/5BAggB0dHT/pUAAdHR0/5JAAHR0dP//QNpAAKioqP//QLJAAIiIiP//QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QMxA'
chr_knight_rnx = 'FBQVAP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9AzUAAiIiI//9AskAAqKio//9A2kAAdHR0/5JAAHR0dP+lQIIAdHR0/5BAggCIiIj/kECCAIiIiP+QQIIAiIiI/6VAAIiIiP+SQACIiIj//0CeQADc3Nz/zUCCAHR0dP+PQIQAdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AAIiIiP+CAPyYAP8AdHR0/45AggCIiIj/gQB0dHT/j0CCAIiIiP//QJ1AANzc3P/gQAB0dHT/QAB0dHT/QAB0dHT/jUAAqKio/wD8mAD/AIiIiP8A/JgA/wB0dHT/APyYAP8AdHR0/4xAAKioqP+EAPyYAP8AdHR0/4xAAKioqP+EAPyYAP8AdHR0/4xAALi4uP+EAPyYAP8AdHR0/4xAALi4uP+EAPyYAP8AdHR0/4xAAOzs7P8A/JgA/wCIiIj/APyYAP8AiIiI/wD8mAD/AHR0dP+NQACIiIj/QACIiIj/QACIiIj//0CIQADc3Nz/kkAARERE/5JAAKioqP+mQADMmGT/pECBAHR0dP9AgQB0dHT/jUAAqKio/4EA/JgA/wCIiIj/gQD8mAD/AHR0dP+MQACoqKj/AIiIiP+EAPyYAP8AdHR0/4tAAKioqP+FAPyYAP8AdHR0/4tAALi4uP8AiIiI/4QA/JgA/wB0dHT/i0AAuLi4/wCIiIj/hAD8mAD/AHR0dP+LQAC4uLj/gQD8mAD/AIiIiP+BAPyYAP8AdHR0/41AgQCIiIj/QIEAiIiI//9AiEAA3Nzc/5JAAERERP+SQACoqKj/kkAARERE/5JAAERERP+kQAB0dHT/QAB0dHT/QAB0dHT/jkAA/JgA/wDMmDD/ggD8mAD/AHR0dP+OQIQA/JgA/wB0dHT/jECEAPyYAP+BAHR0dP+NQIMA/JgA/4EAdHR0/41AhAD8mAD/AHR0dP+MQAD8mAD/AMyYMP+CAPyYAP8AdHR0/41AAIiIiP9AAIiIiP9AAIiIiP//QIhAAKioqP+SQABERET/kkAAdHR0/5JAAERERP+SQADMmGT/pUCCAHR0dP+PQAD8mAD/APzMMP+BAPyYAP8AiIiI/49AABAQEP+CAPyYAP+BAHR0dP+NQAD8zJj/gQD8mAD/AHR0dP+PQAD8zJj/gQD8mAD/AHR0dP+PQAAQEBD/ggD8mAD/gQB0dHT/jECDAPyYAP8AiIiI/49AggCIiIj//0CJQACoqKj/kkAARERE/5JAAHR0dP+mQACYZDD/uEAA/JgA/0CCAPyYAP+PQAD8mGT/gwD8mAD/jkAA/Jhk/4IA/JgA/49AAPzMmP+CAPyYAP+PQAD8zJj/gwD8mAD/jUAA/JgA/0AA/Jgw/4EA/JgA/5FAAPyYAP//QJ1AAKioqP+6QACYZDD/uUAA/JgA/wAAmDD/APyYAP+PQIQA/JgA/49AADDMAP+DAPyYAP+OQAAwzDD/gwD8mAD/jUCDAPyYAP8A/Jgw/49AAPyYAP8AAJgw/4IA/JgA/6VAAPyYAP+kQAD8mAD/9kAAqKio/6ZAAJhkMP+5QAD8mAD/APzMmP+RQAAwzDD/APyYAP8AMMww/5BAAACYMP8A/JgA/wAAmDD/kEAAMMww/wD8mAD/ADDMMP+QQAAwzDD/gQAwmGT/AGSYMP8A/JgA/45AAPyYAP+TQAD8zJj/gUAA/JgA/8xAAPyYAP//QIlAAJhkMP+mQAAwmGT/pUAAMMww/wAAmDD/ADDMMP+QQAAAmDD/APyYAP8AAJgw/5BAADDMMP8A/JgA/wAwzDD/kEAAAJgw/wAwzDD/AACYMP+UQAD8mAD/o0AA/MyY/4FAAPyYAP+lQAD8mAD//0CcQACYZDD/kkAA/MyY/6RAAACYMP8AMMww/wAAmDD/ADDMMP8AAJgw/45AgQAwzDD/APyYAP+BADDMMP+OQIQAAJgw/45AhAAwzDD/jkCBAACYMP8A/JgA/4EAAJgw/45AADDMMP8AAJgw/wAwzDD/AACYMP8AMMww/5BAAPzMmP+BQAD8mAD/pkAA/JgA//9Ar0AAmGQw/85AAPzMmP+6QAD8zJj//0D/QIJAAJhkMP/OQACYZDD/ukAAmGQw//9A/0CCQACYZDD/zkAAmGQw/7pAAJhkMP//QKhA'
chr_knight_rpy = 'FBUUAP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QMpAggC4uLj/ggCoqKj/jUAA7Ozs/4EAuLi4/4IAqKio//9A/UAAMMww/wAAmDD/ADDMMP8AAJgw/wAwzDD/AACYMP+2QAD8mAD/gUAA/JgA/45AAPyYAP+DQAD8mAD/jUAA/JgA/4NAAPyYAP+MQACIiIj/APyYAP+BQAD8mAD/QAD8mAD/AHR0dP+LQACIiIj/APyYAP+BAIiIiP8A/JgA/wCIiIj/APyYAP8AdHR0/4tAAIiIiP+FAPyYAP8AdHR0/4xAhACIiIj/AHR0dP//QOlAgQAAmDD/ADDMMP8AAJgw/4EAMMww/45AAACYMP8AMMww/wAAmDD/ADDMMP+OQAD8mAD/gQAwzDD/AACYMP8AMMww/wD8mAD/jUCBAPyYAP8AMMww/wAwzAD/gQD8mAD/jkCBAPzMmP+BAPyYZP+NQACIiIj/APyYAP8AEBAQ/4EA/MyY/wAQEBD/APzMMP8AdHR0/4xAAMyYMP+DAPyYAP8AzJgw/4xAAIiIiP+FAPyYAP8AdHR0/4xAAIiIiP+DAPyYAP8AiIiI/4xAgQCIiIj/gwD8mAD/gQB0dHT/jUCCAIiIiP8AdHR0//9Am0AAmGQw/4FAAJhkMP+CQACYZDD/i0AAmGQw/4FAAJhkMP+CQACYZDD/i0AA/MyY/4FAAPzMmP+CQACYZDD/iUAA/MyY/wAwzDD/APyYAP8AMMww/wAAmDD/APyYAP8AAJgw/0AA/MyY/wCYZDD/iEAA/MyY/4FAADDMMP+BAPyYAP8AAJgw/0AAMJhk/0AAmGQw/4lAAPzMmP9AADCYZP+CAPyYAP8A/MyY/4FAAJhkMP9AAKioqP+EQAD8mAD/gkAAAJgw/4MA/JgA/wAAmDD/gUAAmGQw/4FAAKioqP+HQAD8mDD/hAD8mAD/gUAAmGQw/0AAdHR0/wBERET/AKioqP+FQACIiIj/hQD8mAD/AHR0dP9AAMyYZP8ARERE/wB0dHT/AERERP8AqKio/4VAAIiIiP+FAPyYAP8AdHR0/0CBAERERP8AqKio/wBERET/ANzc3P+GQACIiIj/gwD8mAD/AIiIiP+BQADMmGT/QACoqKj/AERERP8A3Nzc/4VAAIiIiP+FAPyYAP8AdHR0/4NAANzc3P+GQIEAiIiI/4MA/JgA/4EAdHR0/4JAANzc3P+GQIEAiIiI/0CCAIiIiP8AdHR0/0CBAHR0dP+JQACoqKj/h0AAiIiI//9Av0CBAACYMP8AMMww/wAAmDD/gQAwzDD/jkAAAJgw/wAwzDD/AACYMP8AMMww/4lAAPyYAP+EQAAwmGT/ADDMMP8AAJgw/wAwzDD/jkCFAPyYAP+MQIYA/JgA/4xAAIiIiP+FAPyYAP8AdHR0/4xAhQD8mAD/jEAAiIiI/4UA/JgA/wB0dHT/jEAAiIiI/4MA/JgA/wB0dHT/jEAAiIiI/wB0dHT/gwD8mAD/gQB0dHT/jUCCAIiIiP8AdHR0//9A1kAAMMww/wAAmDD/ADDMMP8AAJgw/wAwzDD/AACYMP+JQAD8mAD/l0AAZJgw/49AAPyYAP9AAPyYAP8A/Jgw/4IA/JgA/45AhQD8mAD/jUAAiIiI/wD8mAD/gQB0dHT/APyYAP8AiIiI/4xAAIiIiP+FAPyYAP8AdHR0/4tAAIiIiP+FAPyYAP8AdHR0/4tAAIiIiP+FAPyYAP8AdHR0/4xAhQB0dHT//0DmQAD8mAD/QAD8mAD/kUAA/JgA/0AA/JgA/5FAAPyYAP9AAPyYAP+RQAD8mAD/QIEA/JgA/5BAAPyYAP+BQAD8mAD/j0AAdHR0/4FAAHR0dP+OQAB0dHT/APyYAP+BAHR0dP8A/JgA/wB0dHT/jUAAdHR0/4MA/JgA/wB0dHT/jUCFAHR0dP//QP9A4kAAdHR0/4FAAHR0dP+PQIMAdHR0/49AgwB0dHT//0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9Ag0A='
chr_knight_rny = 'FBUUAP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0DbQAB0dHT/gUAAdHR0/49AgwB0dHT/j0CDAHR0dP//QP9AmEAA/JgA/0AA/JgA/49AAPyYAP9AAPyYAP+PQAD8mAD/QAD8mAD/jkCBAPyYAP9AAPyYAP+OQAD8mAD/gUAA/JgA/49AAHR0dP+BQAB0dHT/jkAAdHR0/wD8mAD/gQB0dHT/APyYAP8AdHR0/41AAHR0dP+DAPyYAP8AdHR0/41AhQB0dHT//0D9QAAAmDD/ADDMMP8AAJgw/wAwzDD/AACYMP8AMMww/5ZAAPyYAP+NQABkmDD/j0CCAPyYAP8A/Jgw/wD8mAD/QAD8mAD/i0CFAPyYAP+NQACIiIj/APyYAP+BAHR0dP8A/JgA/wCIiIj/jEAAdHR0/4UA/JgA/wCIiIj/i0AAdHR0/4UA/JgA/wCIiIj/i0AAdHR0/4UA/JgA/wCIiIj/jECFAHR0dP//QOlAgQAwzDD/AACYMP8AMMww/4EAAJgw/45AADDMMP8AAJgw/wAwzDD/AACYMP+PQAAwzDD/AACYMP8AMMww/wAwmGT/hEAA/JgA/4hAhQD8mAD/jUCGAPyYAP+LQAB0dHT/hQD8mAD/AIiIiP+MQIUA/JgA/4xAAHR0dP+FAPyYAP8AiIiI/4xAAHR0dP+DAPyYAP8AiIiI/4xAgQB0dHT/gwD8mAD/AHR0dP8AiIiI/41AAHR0dP+CAIiIiP//QJdAAJhkMP+CQACYZDD/gUAAmGQw/4tAAJhkMP+CQACYZDD/gUAAmGQw/4tAAJhkMP+CQAD8zJj/gUAA/MyY/4tAAJhkMP8A/MyY/0AAAJgw/wD8mAD/AACYMP8AMMww/wD8mAD/ADDMMP8A/MyY/4lAAJhkMP9AADCYZP9AAACYMP+BAPyYAP8AMMww/4FAAPzMmP+GQACoqKj/QACYZDD/gUAA/MyY/4IA/JgA/wAwmGT/QAD8zJj/hkAAqKio/4FAAJhkMP+BQAAAmDD/gwD8mAD/AACYMP+CQAD8mAD/gkAAqKio/wBERET/AHR0dP9AAJhkMP+BQIQA/JgA/wD8mDD/hkAAqKio/wBERET/AHR0dP8ARERE/wDMmGT/QAB0dHT/hQD8mAD/AIiIiP+FQADc3Nz/AERERP8AqKio/4EARERE/0AAdHR0/4UA/JgA/wCIiIj/hUAA3Nzc/wBERET/AKioqP9AAMyYZP+BQACIiIj/gwD8mAD/AIiIiP+HQADc3Nz/g0AAdHR0/4UA/JgA/wCIiIj/h0AA3Nzc/4JAgQB0dHT/gwD8mAD/gQCIiIj/ikCBAHR0dP9AAHR0dP+CAIiIiP9AgQCIiIj/iUAAiIiI/4dAAKioqP//QL9AgQAwzDD/AACYMP8AMMww/4EAAJgw/45AADDMMP8AAJgw/wAwzDD/AACYMP+OQAD8mAD/ADDMMP8AAJgw/4EAMMww/wD8mAD/jUCBAPyYAP8AMMwA/wAwzDD/gQD8mAD/jkCBAPyYZP+BAPzMmP+NQAB0dHT/APzMMP8AEBAQ/4EA/MyY/wAQEBD/APyYAP8AiIiI/4xAAMyYMP+DAPyYAP8AzJgw/4xAAHR0dP+FAPyYAP8AiIiI/4xAAIiIiP+DAPyYAP8AiIiI/4xAgQB0dHT/gwD8mAD/gQCIiIj/jUAAdHR0/4IAiIiI//9A1kAAAJgw/wAwzDD/AACYMP8AMMww/wAAmDD/ADDMMP+2QAD8mAD/gUAA/JgA/45AAPyYAP+DQAD8mAD/jUAA/JgA/4NAAPyYAP+MQAB0dHT/APyYAP9AAPyYAP+BQAD8mAD/AIiIiP+LQAB0dHT/APyYAP8AiIiI/wD8mAD/gQCIiIj/APyYAP8AiIiI/4tAAHR0dP+FAPyYAP8AiIiI/4xAAHR0dP+EAIiIiP//QP9A9UCCAKioqP+CALi4uP+NQIIAqKio/4EAuLi4/wDs7Oz//0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9A/0D/QP9AtkA='
chr_knight_rpz = 'FRQUAP9Aw0CBAKioqP+BANzc3P//QP9A/0CeQACoqKj/gwBERET/ANzc3P//QP9A/0CcQACoqKj/QIEAdHR0/4EAqKio/0AA3Nzc//9A/0D/QJ5AgQBERET//0D/QP9AmUCHAJhkMP8AzJhk/wBERET/AMyYZP//QP9A/0CbQAD8zJj/iEAAdHR0/wCIiIj//0D/QPNAggB0dHT/kEAAdHR0/0AAdHR0/0AAdHR0/4tAADCYZP+CQIEAdHR0/0CCAHR0dP+OQAB0dHT/QAB0dHT/QAB0dHT/kECCAHR0dP//QP9At0CCAHR0dP+LQAAAmDD/gkAA/JgA/wCIiIj/ggD8mAD/AHR0dP+KQAAwzDD/gUCEAPyYAP+BAHR0dP+KQAAAmDD/QAD8zJj/AACYMP+CAPyYAP8AiIiI/wD8mAD/AHR0dP+KQAAwzDD/QIEA/JgA/0AA/Mww/wDMmDD/APyYAP8AiIiI/wB0dHT/ikAAAJgw/4JAhAD8mAD/AHR0dP+RQIEAqKio//9A/0CMQIIAdHR0/5BAAPyYAP8AdHR0/4EA/JgA/wB0dHT/i0AAMMww/4FAhQD8mAD/AHR0dP+KQIIAMMww/4YA/JgA/wB0dHT/hkCBAJhkMP8A/MyY/wD8mAD/AACYMP+HAPyYAP8AdHR0/4lAggAwzDD/APyYAP8A/Jhk/wAQEBD/gwD8mAD/AHR0dP+JQAAwzDD/gUAA/JgA/4JAAIiIiP8A/JgA/wCIiIj/kUCBAKioqP//QP9AjUCBAHR0dP+PQAD8mAD/gUAAdHR0/wD8mAD/AHR0dP+LQAAAmDD/gUCBAPyYAP8AdHR0/4IA/JgA/wB0dHT/ikCCAACYMP+GAPyYAP8AiIiI/4lAAACYMP+IAPyYAP8AiIiI/4lAggAAmDD/ADDMAP8A/Jhk/wD8zJj/gwD8mAD/AIiIiP+JQAAAmDD/hECCAPyYAP8AiIiI/5FAgQCoqKj//0D/QI1AgQB0dHT/j0AA/JgA/4FAAHR0dP8A/JgA/wB0dHT/i0AAMMww/4FAgQD8mAD/AHR0dP+CAPyYAP8AdHR0/4pAggAwzDD/hgD8mAD/AIiIiP+JQAAwzDD/iAD8mAD/AIiIiP+JQIMAMMww/4EA/MyY/4MA/JgA/wCIiIj/iUAAMMww/4VAAIiIiP8A/JgA/wCIiIj/kUCBALi4uP//QP9AjECCAHR0dP+OQAD8mAD/QAD8mAD/AHR0dP+BAPyYAP8AdHR0/4tAAACYMP9AAGSYMP8A/Jgw/4QA/JgA/wB0dHT/ikCBAACYMP8AMJhk/4YA/JgA/wCIiIj/hkCBAJhkMP8A/MyY/wD8mAD/ADDMMP8AMJhk/4YA/JgA/wCIiIj/iUCBAACYMP8AMMww/wD8mAD/APzMmP8AEBAQ/4MA/JgA/wCIiIj/iUAAAJgw/4FAAPyYAP+CQACIiIj/APyYAP8AiIiI/5FAgQC4uLj//0D/QJ1AAPyYAP9AAPyYAP+BQIIAdHR0/4tAADDMMP+BQIEA/JgA/wCIiIj/ggD8mAD/AHR0dP+KQAAAmDD/gUCEAPyYAP8AiIiI/wB0dHT/ikAAMMww/4FAAACYMP8A/Jgw/4EA/JgA/wCIiIj/APyYAP8AiIiI/4pAAACYMP9AgQD8mAD/QAD8mAD/AMyYMP8A/JgA/4EAiIiI/4pAADDMMP+CQIQA/JgA/wCIiIj/kUAAuLi4/wDs7Oz//0D/QJxAAPyYAP9AAPyYAP+XQIIAiIiI/49AAPyYAP8AiIiI/0AAiIiI/0AAiIiI/4pAAPzMmP9AAPzMmP+BQIEAiIiI/0CCAIiIiP+OQACIiIj/QACIiIj/QACIiIj/kECCAIiIiP//QP9AskAA/JgA/5VAAPyYAP+mQAD8zJj/h0AAiIiI/wCoqKj//0D/QNhAAPyYAP//QP9A/0C4QAD8mAD/qkAA/JgA//9A/0D/QIxAAPyYAP//QP9A/0D/QP9A/0D/QP9AvUA='
chr_knight_rnz = 'FRQUAP9A20CBANzc3P+BAKioqP//QP9A/0CeQADc3Nz/gwBERET/AKioqP//QP9A/0CcQADc3Nz/QIEAqKio/4EAdHR0/0AAqKio//9A/0D/QJ5AgQBERET//0D/QP9AoEAAzJhk/wBERET/AMyYZP+HAJhkMP//QP9A/0CUQACIiIj/AHR0dP+IQAD8zJj//0D/QPBAggB0dHT/kEAAdHR0/0AAdHR0/0AAdHR0/45AggB0dHT/QIEAdHR0/4JAADCYZP+LQAB0dHT/QAB0dHT/QAB0dHT/kECCAHR0dP//QP9At0CBAKioqP+RQAB0dHT/hAD8mAD/gkAAAJgw/4pAAHR0dP8AiIiI/wD8mAD/AMyYMP8A/Mww/0CBAPyYAP9AADDMMP+KQAB0dHT/APyYAP8AiIiI/4IA/JgA/wAAmDD/APzMmP9AAACYMP+KQIEAdHR0/4QA/JgA/4FAADDMMP+KQAB0dHT/ggD8mAD/AIiIiP8A/JgA/4JAAACYMP+LQIIAdHR0//9A/0CiQIEAqKio/5FAAIiIiP8A/JgA/wCIiIj/gkAA/JgA/4FAADDMMP+JQAB0dHT/gwD8mAD/ABAQEP8A/Jhk/wD8mAD/ggAwzDD/iUAAdHR0/4cA/JgA/wAAmDD/APyYAP8A/MyY/4EAmGQw/4ZAAHR0dP+GAPyYAP+CADDMMP+KQAB0dHT/hQD8mAD/gUAAMMww/4tAAHR0dP+BAPyYAP8AdHR0/wD8mAD/kECCAHR0dP//QP9AjECBAKioqP+RQACIiIj/ggD8mAD/hEAAAJgw/4lAAIiIiP+DAPyYAP8A/MyY/wD8mGT/ADDMAP+CAACYMP+JQACIiIj/iAD8mAD/AACYMP+JQACIiIj/hgD8mAD/ggAAmDD/ikAAdHR0/4IA/JgA/wB0dHT/gQD8mAD/gUAAAJgw/4tAAHR0dP8A/JgA/wB0dHT/gUAA/JgA/49AgQB0dHT//0D/QI1AgQC4uLj/kUAAiIiI/wD8mAD/AIiIiP+FQAAwzDD/iUAAiIiI/4MA/JgA/4EA/MyY/4MAMMww/4lAAIiIiP+IAPyYAP8AMMww/4lAAIiIiP+GAPyYAP+CADDMMP+KQAB0dHT/ggD8mAD/AHR0dP+BAPyYAP+BQAAwzDD/i0AAdHR0/wD8mAD/AHR0dP+BQAD8mAD/j0CBAHR0dP//QP9AjUCBALi4uP+RQACIiIj/APyYAP8AiIiI/4JAAPyYAP+BQAAAmDD/iUAAiIiI/4MA/JgA/wAQEBD/APzMmP8A/JgA/wAwzDD/gQAAmDD/iUAAiIiI/4YA/JgA/wAwmGT/ADDMMP8A/JgA/wD8zJj/gQCYZDD/hkAAiIiI/4YA/JgA/wAwmGT/gQAAmDD/ikAAdHR0/4QA/JgA/wD8mDD/AGSYMP9AAACYMP+LQAB0dHT/gQD8mAD/AHR0dP8A/JgA/0AA/JgA/45AggB0dHT//0D/QIxAAOzs7P8AuLi4/5FAAIiIiP+EAPyYAP+CQAAwzDD/ikCBAIiIiP8A/JgA/wDMmDD/APyYAP9AgQD8mAD/QAAAmDD/ikAAiIiI/wD8mAD/AIiIiP+BAPyYAP8A/Jgw/wAAmDD/gUAAMMww/4pAAHR0dP8AiIiI/4QA/JgA/4FAAACYMP+KQAB0dHT/ggD8mAD/AIiIiP+BAPyYAP+BQAAwzDD/i0CCAHR0dP+BQAD8mAD/QAD8mAD//0D/QLJAggCIiIj/kEAAiIiI/0AAiIiI/0AAiIiI/45AggCIiIj/QIEAiIiI/4FAAPzMmP9AAPzMmP+KQACIiIj/QACIiIj/QACIiIj/APyYAP+PQIIAiIiI/5dAAPyYAP9AAPyYAP//QP9A2EAAqKio/wCIiIj/h0AA/MyY/6ZAAPyYAP+VQAD8mAD//0D/QP9Ao0AA/JgA//9A/0DgQAD8mAD/qkAA/JgA//9A/0D/QIxAAPyYAP//QP9A/0D/QP9A/0D/QPRA'
chr_knight_mx  = 'FBUUAP9AlEAAqKio/5JAAKioqP+SQADc3Nz/kkAA3Nzc//9A/0DSQACoqKj/kkAARERE/5JAAERERP+SQABERET/kkAARERE/5JAANzc3P//QP9AqkAAqKio/6ZAAHR0dP+SQAB0dHT/kkAAqKio/5JAAKioqP+mQADc3Nz//0D/QNJAAERERP+SQABERET//0DuQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAMyYZP+SQABERET/kkAAzJhk//9A/0CWQAD8zJj//0DGQAB0dHT/kkAAiIiI//9A2kAAMJhk/81AggB0dHT/j0AAdHR0/0AAdHR0/0AAdHR0/45AgQB0dHT/QIEAdHR0/45AAHR0dP9AAHR0dP9AAHR0dP+PQIIAdHR0/5FAAHR0dP//QNhAAACYMP8AMMww/wAAmDD/ADDMMP8AAJgw/6RAAPzMmP8A/JgA/5BAAPyYAP8AAJgw/wD8mAD/j0CCAPyYAP9AAPyYAP+OQACIiIj/gQD8mAD/APzMMP8A/JgA/41AAHR0dP+CAPyYAP8AzJgw/wD8mAD/jUAAdHR0/4EA/JgA/wCIiIj/gQD8mAD/AKioqP+MQAB0dHT/APyYAP8AdHR0/wD8mAD/AIiIiP8A/JgA/wCoqKj/jUCEAHR0dP//QLBAAJhkMP+SQACYZDD/kkAA/MyY/5BAgQAwzDD/APyYAP+BADDMMP+PQAAwzDD/AACYMP8AMMww/5BAADDMMP8A/JgA/wAwzDD/j0CEAPyYAP+NQIMA/JgA/wD8mGT/jUCBAHR0dP+CAPyYAP8AEBAQ/41AAHR0dP+EAPyYAP+NQAB0dHT/hAD8mAD/AIiIiP8AqKio/4xAAHR0dP+EAPyYAP8AqKio/41AAHR0dP+CAPyYAP8AiIiI/49AggB0dHT//0DXQIQAAJgw/49AAACYMP8A/JgA/wAAmDD/kEAAAJgw/wD8mAD/AACYMP+OQIMA/JgA/wAwzAD/j0CCAPyYAP8A/Jhk/49AAHR0dP+BAPyYAP8A/MyY/41AgQB0dHT/hAD8mAD/jEAAdHR0/4UA/JgA/wCoqKj/jEAAdHR0/4QA/JgA/wCoqKj/jUAAdHR0/4IA/JgA/wCIiIj/j0CCAIiIiP//QNdAhAAwzDD/j0AAMMww/wD8mAD/ADDMMP+QQAAwzDD/APyYAP8AMMww/45AgwD8mAD/ADDMMP+PQIIA/JgA/wD8zJj/j0AAdHR0/4EA/JgA/wD8zJj/jUCBAHR0dP+DAPyYAP+NQAB0dHT/hAD8mAD/AIiIiP8AuLi4/4xAAHR0dP+EAPyYAP8AuLi4/41AAHR0dP+CAPyYAP8AiIiI/49AggCIiIj//0CdQACYZDD/kkAAmGQw/5JAAPzMmP+QQIEAAJgw/wD8mAD/gQAAmDD/j0AAAJgw/wAwzDD/AACYMP+OQAD8mAD/AGSYMP+BADCYZP8AMMww/49AAPyYMP+DAPyYAP+NQIMA/JgA/wD8zJj/jUCBAHR0dP+CAPyYAP8AEBAQ/41AAHR0dP+EAPyYAP+NQAB0dHT/hAD8mAD/AIiIiP8AuLi4/4xAAHR0dP+EAPyYAP8AuLi4/41AAHR0dP+CAPyYAP8AiIiI/49AggCIiIj//0DXQAAwzDD/AACYMP8AMMww/wAAmDD/ADDMMP+NQAD8mAD/lkAA/JgA/45AggD8mAD/AACYMP8A/JgA/49AgQD8mAD/APyYMP9AAPyYAP+OQACIiIj/gwD8mAD/jUAAdHR0/4IA/JgA/wDMmDD/APyYAP+NQAB0dHT/gQD8mAD/AIiIiP+BAPyYAP8AuLi4/4xAAHR0dP8A/JgA/wCIiIj/APyYAP8AiIiI/wD8mAD/AOzs7P+NQIEAdHR0/4IAiIiI//9A6UAA/JgA/4FAAPzMmP+jQAD8mAD/gUAA/MyY/6VAAPyYAP+SQIIAiIiI/49AAIiIiP9AAIiIiP9AAIiIiP+OQIEAiIiI/0CBAIiIiP+OQACIiIj/QACIiIj/QACIiIj/j0CCAIiIiP+RQACIiIj//0DrQAD8mAD/gUAA/MyY/6RAAPyYAP//QIxAAIiIiP+SQACoqKj//0DDQAD8mAD//0D/QP9At0AA/JgA/6hAAPyYAP//QP9A/0CNQAD8mAD//0D/QP9A/0D/QP9A/0D/QP5A'
chr_knight_my  = 'FBUUAP9A0UAA3Nzc/5JAANzc3P+SQACoqKj/kkAAqKio//9A/0DSQADc3Nz/kkAARERE/5JAAERERP+SQABERET/kkAARERE/5JAAKioqP//QP9AqkAA3Nzc/6ZAAKioqP+SQACoqKj/kkAAdHR0/5JAAHR0dP+mQACoqKj//0D/QNJAAERERP+SQABERET//0D/QPpAAMyYZP+SQABERET/kkAAzJhk/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD//0CKQACIiIj/kkAAdHR0//9AxkAA/MyY//9A2kAAdHR0/5FAggB0dHT/j0AAdHR0/0AAdHR0/0AAdHR0/45AgQB0dHT/QIEAdHR0/45AAHR0dP9AAHR0dP9AAHR0dP+PQIIAdHR0/81AADCYZP//QP9AQIQAdHR0/41AAKioqP8A/JgA/wCIiIj/APyYAP8AdHR0/wD8mAD/AHR0dP+MQACoqKj/gQD8mAD/AIiIiP+BAPyYAP8AdHR0/41AAPyYAP8AzJgw/4IA/JgA/wB0dHT/jUAA/JgA/wD8zDD/gQD8mAD/AIiIiP+OQAD8mAD/QIIA/JgA/49AAPyYAP8AAJgw/wD8mAD/kEAA/JgA/wD8zJj/pEAAAJgw/wAwzDD/AACYMP8AMMww/wAAmDD//0DXQIIAdHR0/49AAIiIiP+CAPyYAP8AdHR0/41AAKioqP+EAPyYAP8AdHR0/4xAAKioqP8AiIiI/4QA/JgA/wB0dHT/jUCEAPyYAP8AdHR0/41AABAQEP+CAPyYAP+BAHR0dP+NQAD8mGT/gwD8mAD/jUCEAPyYAP+PQAAwzDD/APyYAP8AMMww/5BAADDMMP8AAJgw/wAwzDD/j0CBADDMMP8A/JgA/4EAMMww/5BAAPzMmP+SQACYZDD/kkAAmGQw//9AnUCCAIiIiP+PQACIiIj/ggD8mAD/AHR0dP+NQACoqKj/hAD8mAD/AHR0dP+MQACoqKj/hQD8mAD/AHR0dP+MQIQA/JgA/4EAdHR0/41AAPzMmP+BAPyYAP8AdHR0/49AAPyYZP+CAPyYAP+PQAAwzAD/gwD8mAD/jkAAAJgw/wD8mAD/AACYMP+QQAAAmDD/APyYAP8AAJgw/49AhAAAmDD//0DXQIIAiIiI/49AAIiIiP+CAPyYAP8AdHR0/41AALi4uP+EAPyYAP8AdHR0/4xAALi4uP8AiIiI/4QA/JgA/wB0dHT/jUCDAPyYAP+BAHR0dP+NQAD8zJj/gQD8mAD/AHR0dP+PQAD8zJj/ggD8mAD/j0AAMMww/4MA/JgA/45AADDMMP8A/JgA/wAwzDD/kEAAMMww/wD8mAD/ADDMMP+PQIQAMMww//9A10CCAIiIiP+PQACIiIj/ggD8mAD/AHR0dP+NQAC4uLj/hAD8mAD/AHR0dP+MQAC4uLj/AIiIiP+EAPyYAP8AdHR0/41AhAD8mAD/AHR0dP+NQAAQEBD/ggD8mAD/gQB0dHT/jUAA/MyY/4MA/JgA/41AgwD8mAD/APyYMP+PQAAwzDD/gQAwmGT/AGSYMP8A/JgA/45AAACYMP8AMMww/wAAmDD/j0CBAACYMP8A/JgA/4EAAJgw/5BAAPzMmP+SQACYZDD/kkAAmGQw//9AsECCAIiIiP+BAHR0dP+NQADs7Oz/APyYAP8AiIiI/wD8mAD/AIiIiP8A/JgA/wB0dHT/jEAAuLi4/4EA/JgA/wCIiIj/gQD8mAD/AHR0dP+NQAD8mAD/AMyYMP+CAPyYAP8AdHR0/41AgwD8mAD/AIiIiP+OQAD8mAD/QAD8mDD/gQD8mAD/j0AA/JgA/wAAmDD/ggD8mAD/jkAA/JgA/5ZAAPyYAP+NQAAwzDD/AACYMP8AMMww/wAAmDD/ADDMMP//QNhAAIiIiP+RQIIAiIiI/49AAIiIiP9AAIiIiP9AAIiIiP+OQIEAiIiI/0CBAIiIiP+OQACIiIj/QACIiIj/QACIiIj/j0CCAIiIiP+SQAD8mAD/pUAA/MyY/4FAAPyYAP+jQAD8zJj/gUAA/JgA//9Aw0AAqKio/5JAAIiIiP//QIxAAPyYAP+kQAD8zJj/gUAA/JgA//9A/0D/QLZAAPyYAP//QP9A40AA/JgA/6hAAPyYAP//QP9A/0CNQAD8mAD//0D/QP9A/0D/QP9A/0CzQA=='
chr_knight_mz  = 'FBUUAP9A/0D/QP9A/0D/QP9AtkAA/JgA//9A/0D/QI9AAPyYAP+kQAD8mAD//0D/QOlAAPyYAP//QP9A/0CzQAD8zJj/gUAA/JgA/6VAAPyYAP//QIhAAIiIiP+SQACoqKj//0DGQAD8zJj/gUAA/JgA/6NAAPzMmP+BQAD8mAD/pEAA/JgA/5BAggCIiIj/j0AAiIiI/0AAiIiI/0AAiIiI/45AgQCIiIj/QIEAiIiI/45AAIiIiP9AAIiIiP9AAIiIiP+PQIIAiIiI/5FAAIiIiP//QNhAADDMMP8AAJgw/wAwzDD/AACYMP8AMMww/5NAAPyYAP+OQAD8mAD/kkAA/JgA/wAAmDD/ggD8mAD/jUAA/JgA/0AA/Jgw/4EA/JgA/45AgwD8mAD/AIiIiP+OQAD8mAD/AMyYMP+CAPyYAP8AdHR0/4xAALi4uP+BAPyYAP8AiIiI/4EA/JgA/wB0dHT/jEAA7Ozs/wD8mAD/AIiIiP8A/JgA/wCIiIj/APyYAP8AdHR0/41AggCIiIj/gQB0dHT//0CwQACYZDD/kkAAmGQw/5JAAPzMmP+QQIEAAJgw/wD8mAD/gQAAmDD/j0AAAJgw/wAwzDD/AACYMP+QQAAwzDD/gQAwmGT/AGSYMP8A/JgA/41AgwD8mAD/APyYMP+PQAD8zJj/gwD8mAD/jkAAEBAQ/4IA/JgA/4EAdHR0/41AhAD8mAD/AHR0dP+LQAC4uLj/AIiIiP+EAPyYAP8AdHR0/4tAALi4uP+EAPyYAP8AdHR0/41AAIiIiP+CAPyYAP8AdHR0/49AggCIiIj//0DXQIQAMMww/49AADDMMP8A/JgA/wAwzDD/kEAAMMww/wD8mAD/ADDMMP+QQAAwzDD/gwD8mAD/jkAA/MyY/4IA/JgA/49AAPzMmP+BAPyYAP8AdHR0/49AgwD8mAD/gQB0dHT/i0AAuLi4/wCIiIj/hAD8mAD/AHR0dP+LQAC4uLj/hAD8mAD/AHR0dP+NQACIiIj/ggD8mAD/AHR0dP+PQIIAiIiI//9A10CEAACYMP+PQAAAmDD/APyYAP8AAJgw/5BAAACYMP8A/JgA/wAAmDD/kEAAMMwA/4MA/JgA/45AAPyYZP+CAPyYAP+PQAD8zJj/gQD8mAD/AHR0dP+OQIQA/JgA/4EAdHR0/4tAAKioqP+FAPyYAP8AdHR0/4tAAKioqP+EAPyYAP8AdHR0/41AAIiIiP+CAPyYAP8AdHR0/49AggCIiIj//0CdQACYZDD/kkAAmGQw/5JAAPzMmP+QQIEAMMww/wD8mAD/gQAwzDD/j0AAMMww/wAAmDD/ADDMMP+QQAAwzDD/APyYAP8AMMww/49AhAD8mAD/j0AA/Jhk/4MA/JgA/45AABAQEP+CAPyYAP+BAHR0dP+NQIQA/JgA/wB0dHT/i0AAqKio/wCIiIj/hAD8mAD/AHR0dP+LQACoqKj/hAD8mAD/AHR0dP+NQACIiIj/ggD8mAD/AHR0dP+PQIIAdHR0//9A10AAAJgw/wAwzDD/AACYMP8AMMww/wAAmDD/o0AA/JgA/wD8zJj/kUAA/JgA/wAAmDD/APyYAP+PQAD8mAD/QIIA/JgA/45AAPyYAP8A/Mww/4EA/JgA/wCIiIj/jkAA/JgA/wDMmDD/ggD8mAD/AHR0dP+MQACoqKj/gQD8mAD/AIiIiP+BAPyYAP8AdHR0/4xAAKioqP8A/JgA/wCIiIj/APyYAP8AdHR0/wD8mAD/AHR0dP+NQIQAdHR0//9A/0BAADCYZP/NQIIAdHR0/49AAHR0dP9AAHR0dP9AAHR0dP+OQIEAdHR0/0CBAHR0dP+OQAB0dHT/QAB0dHT/QAB0dHT/j0CCAHR0dP+RQAB0dHT//0DaQAD8zJj//0DGQAB0dHT/kkAAiIiI//9AikAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQACYZDD/kkAAmGQw/5JAAJhkMP+SQADMmGT/kkAARERE/5JAAMyYZP//QP9A+kAARERE/5JAAERERP//QP9A0kAAqKio/6ZAAHR0dP+SQAB0dHT/kkAAqKio/5JAAKioqP+mQADc3Nz//0D/QKpAAKioqP+SQABERET/kkAARERE/5JAAERERP+SQABERET/kkAA3Nzc//9A/0DSQACoqKj/kkAAqKio/5JAANzc3P+SQADc3Nz//0DQQA=='

model = require './models/chr_knight.json'

describe 'IO', ->
  describe 'constructor', ->
    it 'should accept an object', ->
      io = new IO x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]]]
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(1, 'expected io.x to be 1')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(1, 'expected io.y to be 1')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(1, 'expected io.z to be 1')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined').with.propertyByPath(0, 0, 0).with.properties({r: 128, g: 64, b: 32, a: 255, t: 1, s: 2})
    it 'should accept another instance of IO', ->
      io2 = new IO x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]]]
      io = new IO io2
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(1, 'expected io.x to be 1')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(1, 'expected io.y to be 1')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(1, 'expected io.z to be 1')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined').with.propertyByPath(0, 0, 0).with.properties({r: 128, g: 64, b: 32, a: 255, t: 1, s: 2})
    it 'should accept a Base64IO (inherit from IO)', ->
      io2 = new Base64IO chr_knight
      io = new IO io2
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
  describe 'verify', ->
    it 'should verify the integrity of an IO instance', ->
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]]]}).verify().should.be.true
      new IO({x: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]]]}).verify().should.be.false
      new IO({x: 0, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: 42}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}]],[]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2}],[]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 1, s: 2},{}]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[42]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, b: 32, a: 255, t: 1, s: 2}]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 9000, b: 32, a: 255, t: 1, s: 2}]]]}).verify().should.be.false
      new IO({x: 1, y: 1, z: 1, voxels: [[[{r: 128, g: 64, b: 32, a: 255, t: 8, s: 2}]]]}).verify().should.be.false
  describe 'rotate', ->
    it 'should be able to rotate +x', ->
      io = new Base64IO chr_knight_rnx
      io.rotateX(true)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'should be able to rotate -x', ->
      io = new Base64IO chr_knight_rpx
      io.rotateX(false)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'should be able to rotate +y', ->
      io = new Base64IO chr_knight_rny
      io.rotateY(true)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'should be able to rotate -y', ->
      io = new Base64IO chr_knight_rpy
      io.rotateY(false)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'should be able to rotate +z', ->
      io = new Base64IO chr_knight_rnz
      io.rotateZ(true)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'should be able to rotate -z', ->
      io = new Base64IO chr_knight_rpz
      io.rotateZ(false)
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
  describe 'mirror', ->
    it 'ishould be able to mirror x', ->
      io = new Base64IO chr_knight_mx
      io.mirrorX()
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'ishould be able to mirror y', ->
      io = new Base64IO chr_knight_my
      io.mirrorY()
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
    it 'ishould be able to mirror z', ->
      io = new Base64IO chr_knight_mz
      io.mirrorZ()
      io.should.have.ownProperty('x', 'expected io.x to be defined').equal(20, 'expected io.x to be 20')
      io.should.have.ownProperty('y', 'expected io.y to be defined').equal(21, 'expected io.y to be 21')
      io.should.have.ownProperty('z', 'expected io.z to be defined').equal(20, 'expected io.z to be 20')
      io.should.have.ownProperty('voxels', 'expected io.voxels to be defined')
      JSON.parse(JSON.stringify(io.voxels)).should.eql(model.voxels)
